### ISSUE TITLE
Dans TP2 on affiche dans stdout. Dans TP3 doit-on remplir TAD et afficher stdout pour ce cas?

### ISSUE THREAD

**Issue by LouisEtienneLemire** [guyfrancoeur/INF3135_H2019_TP3#1]

**Comment by usselsabbat** [comment]
Le comportement de ton tp3 doit être identique au comportement de ton tp2.
Donc les entrées et les sorties doivent suivent le même comportement.  

Je ne suis pas sure de bien comprendre ce que tu entends par "doit-on remplir TDA", mais si j'essaye de répondre.  

TDA (type de donnée abstrait) est une façon de représenter tes données, comme par exemple un tableau.
Tu peux ajouter (insérer) des données dans le tableau.  Donc, ton TDA est en fait une représentation sous forme d'arbre binaire ou liste chainé ou pile etc.  Cependant ça reste abstrait à l'utilisation car pour l'utilisation tu auras accès à des méthodes d'insertions, de suppression , de parcouir (foreach, itération) qui te permettra de gérer tes données sans avoir besoin de comprendre comment à été implémenter la structure.  Ton choix de structure devra aller en fonction de la façon que tu comptes utiliser tes données.  Par exemple, si tu veux des données triées, une arbre binaire est tout indiqué (si non prévoir un tri), si tu veux représenter une file d'attente à la banque, une structure de pile n'est pas très approprié. 

Alors, ton TDA est donc type abstrait de donnée pour gérer tes données.
Le stdout est le canal de sortie (écran) ou tu envois les données produit à l'aide de ta structure ex. Liste chainée
 
J'espère que ça pu t'aider.

**Comment by guyfrancoeur** [comment]
Bonjour, 

Bien que la question n'est pas facile à lire la solution semble adéquate.
+ Il faut mettre une description complete et soigné!

Nous allons aussi fermer les questions qui sont répondues.
+ Le créateur de la est-il capable de fermer la question?

Merci
