### ISSUE TITLE
Précisions, pour la structure de vecteurs 

### ISSUE THREAD

**Issue by LauriGui** [guyfrancoeur/INF3135_H2019_TP3#10]
Bonjour,

J'utilise la structure de vecteurs et je ne suis pas sûre de la raison qui nous « oblige » à utiliser des `void*`... Je me suis dis que c'est peut-être, en raison des `include` ou de l'espace mémoire (ou si nous voulions que notre structure accepte des éléments, autres que `uint128_t`), mais sinon, je ne sais vraiment pas... 

À part ça, je ne sais pas si le passage d'une même référence, dans plusieurs fonctions, 
```sh
  int main(){ 
         int x = 0; 
         fct1(&x); 
         printf("%d\n", x); 
         return 0;
  } 
  void fct1(int* x){
         fct2(x);
  }
  void fct2(int* x){
         *x += 2;
  }
```
est quelque chose de déconseillé, mais je ne sais pas si quelqu'un a le même problème que moi ou si quelqu'un saurait comment m'aider... Je passe, en paramètre, une référence et elle reste toujours la même (pas de problème), mais lorsque je change la valeur de ma variable,  elle n'est pas complètement changée... En prenant l'exemple que j'ai mis plus haut, `x` change, dans la fonction `fct2` (x = 2) et ensuite, en revenant à `fct1`, le `x` à été changé (x = 2), mais en revenant au `main`, le `x` est toujours de valeur nulle...
 
P.-S.: Je n'ai pas essayé le code de mon exemple, mais je crois qu'il n'y aurait pas de problème, pour ce code... Dans mon cas, c'est que je passe de `tp3.c` à `outils.c` jusqu'à `structure.c`... Je ne sais pas si ça fait vraiment une différence... 

Merci!

**Comment by josuetorr** [comment]
J'ai testé le code que tu as proposé et la valeur de `x` change a deux dans `main`. Personellemen, j'utilise cette technique et elle fonctionne correctement. J'imagine qu'elle pourrait être déconseillée dans certaine situation parce que tu dois faire attention de ne pas modifié certaines variables. Tu pourrais déclarer le pointeur comme `const` pour ne pas modifier l'adresse mémoire (tu pourrais toujours modifié son contenu). Je ne suis pas sûr de comprends ce que tu veux dire par
> c'est que je passe de tp3.c à outils.c jusqu'à structure.c

En ce qui a trait à `void*` pour les vecteurs, je ne suis pas sûr si je pourrais t'aider parce que je n'utilises pas cette structure.

**Comment by LauriGui** [comment]
@josuetorr,

Merci! 

Oui, j'avais pensé à rajouter `const`, mais comme l'adresse de ma variable ne change pas, sans cet ajout, je me dis que ce ne doit pas être ça mon erreur et comme je veux justement changer le contenu de ma variable, en ajoutant `const`, je ne pourrais plus...

Ce que je voulais dire, c'est qu'en fait j'ai un vecteur, dans mon `main` (`tp3.c`), je le passe à une fonction de `outils.c` qui appelle une autre fonction du même fichier qui le transmet à une fonction de `structure.c` qui modifie une valeur du vecteur.
```ssh
 tp3.c: 
       Vecteur vect; 
       fct1Outils(&vect);

 outils.c:
       void fct1Outils(Vecteur *vect){
                    fct2Outils(vect);
       }
       void fct2Outils(Vecteur *vect){
                    fctStruct(vect);
       } 

 structure.c:
       void fctStruct(Vecteur *vect){
                    modification(vect->valeur);   
       }
```
Voilà, je ne sais pas si c'est plus clair..?

**Comment by josuetorr** [comment]
Ça devrait fonctionner, je fais un truc similaire. J'ai `#include "structure.h"` dans `outils.h`. Je ne suis pas certain si c'est la meilleure façon de le faire par exemple.

**Comment by LauriGui** [comment]
J'ai aussi fait le même `include` que toi et pareil, je ne sais pas si c'est la meilleure façon de faire...

Non, j'ai fait exactement les mêmes passages de paramètres que dans mon précédent commentaire...

**Comment by josuetorr** [comment]
Mais j’ai l’impression que ça devrait être correct étant donné que structure est sa propre entité. Tu pourrais l’utiliser dans un autre programme. Ça donne que pour ce travail, main dépends de outils.c qui dépends de structure. 

Je crois qu’on fait bien :)

**Comment by LauriGui** [comment]
J'ai essayé, mais ça rend ma fonction d'initialisation du vecteur un peut plus compliquée... Je n'arrive pas à lui fournir ce qu'elle veut 😅. Mais j'ai l'impression que de toute façon, ça reviendrait au même...

P.-S.: « modifierVect(&vect); » ne peut pas fonctionner, avec l'esperluette, car ça revient à passer un `Vecteur***` à `modifierVect()` qui attend un `Vecteur**` 😉.

**Comment by guyfrancoeur** [comment]
Allo,

Si vous avez résolu votre cas, et que vos programmes fonctionne bien vous pouvez ignorer mon article.

Parcontre, 
+ le but est obscure pour moi.

Ma question est la suivante pourquoi modifier la structure dans outils.c ?

D'après moi les fonctions qui touchent la structure sont déclarées dans structure.h et implémentées dans structure.c

+ Le main() devrait probablement faire les appels de fonctions de la structure.
+ Les fonctions dans outils devraient probablement retourner ce qui est necessaire pour faire le bon appel (ex ajouter).

Le `Couplage` et `Cohésion` sont les facteurs qui definissent un bon logiciel (un programme de qualité).

voir page 4 : [Mémoire de Matrise - O M Lopez](https://savoirs.usherbrooke.ca/bitstream/handle/11143/1606/MR83692.pdf?sequence=1)

En résumé nous devrions avoir une forte cohésion et un faible couplage.

Je crois que le couplage énoncé ici (dans cet article) est trop fort.  Ce qui augmente la complexité.

**Comment by LauriGui** [comment]
Eurêka! J'ai trouvé le problème haha 😂

Lorsque j'ajoutais une valeur à mon vecteur, je passais la référence d'une variable qui peut changer continuellement... Oups... 😇

En tout cas, merci beaucoup pour l'aide!

**Comment by guyfrancoeur** [comment]
Bonjour,

Complément d'information : les void * sont nécessaire lorsque nous voulons `génériser` une fonction.

Ceci pour quelle soit indépendante du type de données quelle traite.

Donc réutilisable (qui devient potentiellement une librairie, solidement construite `fiable`), d'un programme à l'autre ou même avoir et traiter deux variables qui ne sont pas du même type.

exemple 
```c
int insert_V(void * _v, void * _element){
  //du code indépendant du type de l'élément reçu
  return 1; //succès
}

int init_V(void * _v, size_t _s) {
  _v = malloc(_s);
  if (_v == NULL) return 0; else return 1;
}
```

Code théorique pour illustré un cas générique... Bien sur c'est incomplet mais vous comprennez le sens.

**Comment by LauriGui** [comment]
Parfait, c’est ce que j’avais compris 😊 Par contre, dans votre exemple de `init_V`, vous passer un type `size_t`... Donc, si je comprends bien, votre exemple c’est seulement pour illustrer brièvement une structure, avec types génériques, mais pas nécessairement pour un vecteur? (Juste pour être sûre, car il me semble que sinon, ce serait `sizeof void*` qu’on aurait besoin non..? Donc, le paramètre ne serait pas nécessaire!?)
