### ISSUE TITLE
sqrt resolu

### ISSUE THREAD

**Issue by LouisEtienneLemire** [guyfrancoeur/INF3135_H2019_TP3#13]
Ai-je besoin des décimales ou Exemple sqrt(15) = 3 est valide.

**Comment by LouisEtienneLemire** [comment]
Devons nous implémenter un floorSqrt() ou un sqrt()

**Comment by LauriGui** [comment]
C’est valide, car j’imagine que c’est pour ta boucle qui cherche les diviseurs d’un nombre!? 

Et comme nous cherchons des diviseurs entiers, si la racine de ton nombre donne un nombre à virgule, probablement qu’il ne sera pas compté parmi les diviseurs du nombre et nous ne voulons pas non plus aller plus haut que la racine, car, je ne suis pas sertaine, mais il se pourrait qu’on risquerait de trouver deux fois les mêmes diviseurs... Par exemple, si la racine arrondie de 6 donnerait 3, alors on trouverait deux fois les diviseurs 2 et 3 ({2,3} & {3,2})... 

Bref, c’est plus rapide, sans l’arrondissement, et ce n’est pas vraiment nécessaire d’aller plus haut ;)
