### ISSUE TITLE
pointeur fonction et void*

### ISSUE THREAD

**Issue by MassekMeriam** [guyfrancoeur/INF3135_H2019_TP3#14]
Bonjour tout le monde,
si on a une fonction qui prend en paramètre un pointeur de fonction qui prend un void* comme paramètre, comment peut-on faire le cast du void* lors de l'appel de cette fonction.
Exemple:
int fonction1(int (*f1)( void *  )  ){ 
//instructions 
}
int fonction2(int* p){ 
// instructions
}

Comment dois-je faire pour appeler fonction1 avec fonction2 comme paramètre? 

//int a = fonction1 ( &fonction2) ; 
--> donne : expected ‘int (*)(void *)’ but argument is of type ‘int (*)(int *)’ 

Merci beaucoup.

**Comment by guyfrancoeur** [comment]
Allo,

+ La déclaration de la fonction fonction2 est `int fonction2(int)`
+ La déclaration de la fonction `fonction1` est `int (*)(void *)

Les arguments ne sont pas syncronizé (de même type) void * != int

> //int a = fonction1 ( &fonction2);

devrait surement être, int (*a)(void *) = fonction1;

relire les notes de cours si nécessaire.
