### ISSUE TITLE
Pourquoi réinventer un type bool_t ?

### ISSUE THREAD

**Issue by dbrsseau** [guyfrancoeur/INF3135_H2019_TP3#16]
Dans la section _Plus de détails_ de l'énoncée, soit la ligne suivante

> typedef enum ... bool_t;

Pourquoi voudrions-nous réinventer un type `bool_t` lorsqu'on peut seulement inclure `stdbool.h` et utiliser directement le type `bool` ? Je comprends les deux premières modifications à compléter, mais celle-ci me semble inutile et/ou je ne comprends pas le pourquoi nous devrions faire ça.

**Comment by guyfrancoeur** [comment]
Allo,

Je vais le changer le `nom du type` car il est effectivement pas pertinent.
En fait, il ne s'agit pas de reinventer le type bool, mais de creer un nouveau type pour gèrer le sens d'affichage des nombre

```c
typedef enum ... sort_t;
```

l'énoncé sera mis à jour.

merci!
