### ISSUE TITLE
Est-ce possible d'utiliser la fonction de tri qsort() ?

### ISSUE THREAD

**Issue by hervesavidetove** [guyfrancoeur/INF3135_H2019_TP3#17]
Bonsoir,
Sommes-nous autorisé a utiliser  la fonction qsort() pour le tri ou devrons nous en écrire une de toute piece?
qsort() est elle une fonction standard? Je n'ai rien trouvé sur le net quant au fait qu'elle soit standard ou non.
Merci d'avance

**Comment by guyfrancoeur** [comment]
Bonsoir,

Vous pouvez l'utiliser!
