### ISSUE TITLE
Possible erreur dans les fichiers .res ?

### ISSUE THREAD

**Issue by dbrsseau** [guyfrancoeur/INF3135_H2019_TP3#18]
@guyfrancoeur est-il possible qu'il y est des erreurs dans les fichiers `.res` des tests ? Par exemple, le fichier `data6.res` n'est pas ordonné, ni croissant, ni décroissant. S'il faut spécifier un ordre par défaut, je m'attends à ce que les fichiers `.res` soit ordonnés d'un sens ou de l'autre, sinon je ne comprends pas ton résultat.

**Comment by guyfrancoeur** [comment]
Bonjour,

Je crois que vous êtes surement en mesure de faire le nécessaire pour créer des fichiers qui sont à la hauteur de vos besoins.

Mais pour ceux qui voudrait des fichiers, j'ai rendu ceci disponible.

Voici le fichier de données ZIP pour le TP3 au cas ou! [tp3-data.zip](https://github.com/guyfrancoeur/INF3135_H2019/raw/master/tp3/tp3-data.zip)

Je ne sais pas s'ils sont convenable. Une vérification est surement une bonne idée.

**Comment by dbrsseau** [comment]
Non, mais ça me dérange pas d'utiliser les fichiers existants ou de m'en créer un sur mesure pour d'autres tests. Ici je parle d'un fichier de résultat valide alors SI c'est bel et bien un résultat valide pouvez-vous me l'expliquer ? Selon l'énoncé, on doit spécifier un ordre par défaut donc tous les résultats devraient être ordonnés. Je comprends juste pas votre résultat initial... :confused:

**Comment by guyfrancoeur** [comment]
Allo,

Lors du TP2 nous n'avions pas le tri de nos résultats, donc les fichiers étaient en fonction de cette réalité (cette fonctionnalité).

Pour le TP3, nous avons une nouvelle demande, et celle ci rend les fichiers (de résultats) incompatibles et invalides avec la nouvelle demande et le tri par default.

Donc, il est nécessaire de produire des fichiers qui sont adéquats pour nos tests, les fonctionnalités demandées et les résultats attendus.
