### ISSUE TITLE
Plusieurs intervalles dans stdin? (Une entrée au clavier)

### ISSUE THREAD

**Issue by LouisEtienneLemire** [guyfrancoeur/INF3135_H2019_TP3#2]

**Comment by LouisEtienneLemire** [comment]
Il m'est venu la question lorsque je suis arrivé à stdin... Il existe des fichiers.in à plusieurs intervalles. Comment gère-t-on les multiples intervalles dans stdin? Est-ce que le programme peut accepter plusieurs intervalles en entrées au clavier? (stdin)

**Comment by usselsabbat** [comment]
Oui, mais il faudrait vérifier que tu choisisses ce qui identifie la fin de ta lecture.  

Une lecture en général se caractérise par une suite de caractère suivi de la touche enter..  
C’est-a-dire , Tu écris autant de chiffre que tu veux séparé d’un espace et quand tu appuie sur enter alors là il va recuperer tout les intervalles.
Il n’en tiens qu’a Toi maintenant à faire l’interprétation  de cette suite de caractère selon tes besoin.
