### ISSUE TITLE
Lecture - Fonction fgets

### ISSUE THREAD

**Issue by joeybara** [guyfrancoeur/INF3135_H2019_TP3#20]
Lors du TP précédent nous devions lire une ligne seulement par fichier. La fonction fgets fonctionnait à merveille dans ma gestion des inputs. Maintenant qu'on doit géré plus d'une ligne, je pensais garder le même code dans une boucle while pour parcourir ligne par ligne. 

Par contre, si on ne fournit pas de fichier d'entrer, le retour à ligne du terminal après avoir saisie manuellement notre intervalle n'est plus en mesure d’arrêter la saisie. 

Donc, je pensais valider les arguments d'entrées et me créer deux méthodes, mais avec les redirections ça devient un réel casse-tête. J'ai fais quelques recherches et j'ai découvert qu'il était possible de saisir le symbole EOF comme ceci  : [ctrl-d]

(https://stackoverflow.com/questions/11968558/how-to-enter-the-value-of-eof-in-the-terminal). 

Alors je veux savoir si la saisie au clavier doit obligatoirement ce terminer par un retour à la ligne ou si je peux utiliser le ctrl-d ? Advenant le cas ou je dois obligatoirement utiliser le retour à ligne, j'aimerais avoir une piste de solution sur le "comment" s'y prendre car je tourne en rond depuis deux jours.

**Comment by btaousoussema** [comment]
Tu parles d'intervalles saisis manuellement, mais je ne pense pas qu'il y en ait. Soit le fichier est indiqué avec le -i, soit il est en redirection(donc de l'entrée standard), mais pas d'intervalle entré manuellement. Donc, à moins que je ne me sois trompé, le cas qui te pose problème, n'est pas présent. La fin de lecture de fichier est bien EOF.

**Comment by dbrsseau** [comment]
@btaousoussema tu as raison de dire que le prof ne semble pas le valider dans ses tests, mais dans l'énoncé il est clairement indiqué que la ligne de commande suivante : `./tp3 -c BROD11038701` doit être valide. (Elle l'était pour le TP1 et TP2) Si tu ne fournis aucun fichier d'entré alors tu dois saisir l'intervalle manuellement.

**Comment by LauriGui** [comment]
@dbrsseau,

C'est exact. Donc, dans ce cas, c'est effectivement `ctrl-d` qu'on utilise, comme avec une majorité des commandes de `Linux`, si je ne me trompe pas. ;) 
Par exemple, si tu essaie d'entrer simplement la commande `cat`, sur ton terminal, la commande va attendre que tu lui fournisse le contenu d'un fichier (donc tu écris un nouveau fichier, durant l'exécution de la commande, sans avoir eu besoin de le créé au préalable. Bien sûr, lorsque la commande aura terminé son exécution, tu ne verras aucun fichier correspondant à celui que tu as saisi puisque ce n'est pas enregistré, c'est plutôt comme un fichier temporaire.) Bref, pour indiquer à `cat` la fin de ton fichier temporaire, tu dois entrer `ctrl-d`. ;) Un autre moyen d'arrêter l'exécution serait d'entrer `ctrl-c`, mais dans ce cas, le programme ou la commande sera simplement interrompu, donc aucun résultat d'exécution ne sera affiché.

J'espère que ça pourra vous être utile. :)

**Comment by joeybara** [comment]
@LauriGui Super merci !
