### ISSUE TITLE
Boucles sur le serveur JAVA

### ISSUE THREAD

**Issue by robinstpierre** [guyfrancoeur/INF3135_H2019_TP3#22]
Bonjour,

Presque la totalité des coeurs CPU sur le serveur java.labunix.uqam.ca sont à 100%. Il y a plusieurs ./tp2 et ./a.out en cours d'exécution depuis plusieurs centaines d'heures.

SVP vérifiez si vous avez process qui roulent et terminez les afin de ne pas monopoliser les ressources CPU.

**Comment by guyfrancoeur** [comment]
Bonjour,

Utiliser `timeout` pour lancer vos commandes.
