### ISSUE TITLE
Questions par rapport au fichier de correction et evaluer.sh/evaluer-tp3.sh

### ISSUE THREAD

**Issue by fadifeghaly** [guyfrancoeur/INF3135_H2019_TP3#23]
Bonsoir  @guyfrancoeur,

- Si j'ai bien compris, le nom du script de correction pour le tp3 est evaluer-tp3.sh et non evaluer.sh, par contre dans le fichier inf3135-h2019-tp3.correction, quelque test ( précisément 31 -> 36) s'exécutent avec evaluer.sh? 

- Le test de la ligne 33 (./evaluer.sh > evaluer-tp2.guy) me semble bizarre, il est supposé rediriger le output de notre script evaluer vers evaluer-tp2.guy, mais le script part en boucle infinie.

Merci! 
Fadi

**Comment by guyfrancoeur** [comment]
Allo,

Voir les articles qui sont fermés (closed).

**Comment by fadifeghaly** [comment]
Oups! Je ne savais pas que la question a été posée dans un ancien article🙄 Je vais lire les commentaires des autres. 

Merci
