### ISSUE TITLE
Test 32, 34 et 35

### ISSUE THREAD

**Issue by dbrsseau** [guyfrancoeur/INF3135_H2019_TP3#24]
Bonjour, quelqu'un peut m'expliquer les tests 32, 34 et 35 ? Je passe tous les autres, mais ceux-ci me donne du fil à retord et je crois que c'est parce que je ne saisis pas vraiment ce que le prof @guyfrancoeur tente de valider avec ces 3 tests-là. Merci ! :smile:

**Comment by onwilliam** [comment]
Bonjour,

J'étais bloqué sur ces trois tests aussi. Je me suis rendu compte que la méthode eval  n'exécute pas bien ces commandes. Donc, il faudrait utiliser une autre commande. 
Ces trois tests ont tous une chose en commun... Tu peux jeter un coup d'oeil à la fonction `bash` pour régler ce problème.

**Comment by joeybara** [comment]
@onwilliam Super ! J'avais ce problème aussi et tu viens de me sauver la vie :D !

**Comment by dbrsseau** [comment]
Effectivement, un gros merci. Je n'ai pas réussi encore à le faire fonctionner aussi facilement que je l'espérait, mais ta réponse m'a confirmé ce que je pensais ! :smile:
