### ISSUE TITLE
Make valgrind?

### ISSUE THREAD

**Issue by onwilliam** [guyfrancoeur/INF3135_H2019_TP3#27]
Bonjour,

Pour le make valgrind je ne suis pas certain quoi mettre. Il est demandé de soumettre notre programme a valgrind. Cependant, il me semble qu'il faut ajouter les options (-i, -o ,etc) au ./tp3 , sinon le code de retour est autre que 0 quand on rentre seulement (edit: sinon le code de retour n'a pas d'importance?):
`valgrind ./tp3`
Quelqu'un peut-il m'éclaircir svp? merci

**Comment by dbrsseau** [comment]
Une alternative qui fonctionne tu peux enregistrer le output de la commande `valgrind ./tp3` dans une variable comme le code permanent et dans ta cible tu n'as qu'à imprimer (echo) ta variable. Ce n'est peut-être pas l'idéal, mais à dernière minute comme ça règle le problème.
