### ISSUE TITLE
Intégration du code de vector.c

### ISSUE THREAD

**Issue by kd-uqam** [guyfrancoeur/INF3135_H2019_TP3#3]
Si j'ai bien compris ce qui a été dit dans le cours, on est autorisé à mettre le code de [vector.c](https://github.com/guyfrancoeur/INF3135_H2019/blob/master/code/vector.c) directement dans notre code et l'adapter pour les fins du TP, exact?

**Comment by guyfrancoeur** [comment]
Simplement Oui,

Mais attention de ne pas tomber dans le piège de la facilité.

PS : Le vecteur ne doit en aucun temps être initialisé avec une capacité supérieur à 2.
