### ISSUE TITLE
type __int128

### ISSUE THREAD

**Issue by charimene** [guyfrancoeur/INF3135_H2019_TP3#4]
Bonsoir a tous,

a votre avis, est ce normal que la declaration suivante : 
unsigned __int128 entier=134567890123456789012345678901234567890;
me donne les warning suivants : 
1- ISO C does not support ‘__int128’ types [-Wpedantic].
2-integer constant is too large for its type.
en sachant que mon gcc est bien à jour.

Mercii

**Comment by guyfrancoeur** [comment]
Oui,

Normal j'aime ce mot.  Einstein dirait relatif?

Nous, informaticiens, allons dire `voulu` ou `attendu` (*expected*). Le type `__int128` n'est pas dans le standard c99/ISO donc le compilateur donne un avertissement grace à `-pedantic`.  Il nous previent si des parties du code ne sont pas selon le standard.  

Ceci dit c'est le comportement `attendu`.  Car, `__int128` n'est pas encore dans le standard mais supporté dans la liste des `fonctionnalités avancées` (*extended*) ou *extension* du langage.

En terminant, nous ne voulons pas de cet avertissements spécifique! Donc nous allons le gérer afin de le faire disparaître.

**Comment by josuetorr** [comment]
La solution pour que ce message n'apparaisse plus est d'ajouter `__extension__` avant `typedef`.

Par contre, j'ai un problème que je ne suis pas capable de résoudre. J'ai fait beaucoup de recherche, mais je n'arrive pas à trouver une réponse. 

J'ai le code suivant:  

```
unsigned __int128 n = UINT64_MAX + 1;
printU128(&n);
```  
La fonction `printU128` fonctionne parfaitement mais pour des entiers de 64 bit ou moins. Si j'essaie d'afficher `UINT64_MAX` j'obtiens `18446744073709551615`. Par contre, dès que j'essaies d'afficher `UINT64_MAX + 1`, la fonction affiche `0`.

Je ne suis pas totalement certain, mais j'ai l'impression que le serveur JAVA n'interprète pas correctement les `__int128`.

**Comment by guyfrancoeur** [comment]
Bonsoir, 

La version du compilateur est-elle la version 7.3.x ?

**Comment by josuetorr** [comment]
Sur mon ordinateur personnel j’ai la version 7.3.0 de gcc. Sur le serveur JAVA, c’est la version 4.8.5 (Red hat). Par contre, j’obtiens le même résultat sur les deux ordinateurs.

**Comment by charimene** [comment]
Bonjour a tous,
j'ai essaye le 2e bout de code du prof Guy avec n = ~n;
et ca me donne : n = 340282366920938463463374607431768211455 
est ce possible que le maximum d'un unsigned __int128 soit sur 39 digits ?

Mercii :)

**Comment by josuetorr** [comment]
@guyfrancoeur en fait, la fonction printU128 que j'utilises est celle que j'ai écrit moi même. Finalement ça fonctionne quand j'utilises `~n`. Je ne comprends pas encore totalement pourquoi ça fonctionne, je vais essayer de comprendre.

@charimene Oui! Un `unsigned __int128` est 39 digits de long :)

**Comment by charimene** [comment]
Merci @josuetorr

**Comment by charimene** [comment]
Salut,
j'aimerai confirmer SVP est ce que @guyfrancoeur va tester nos programmes avec des nombres de 40 digits ? parce que effectivement unsigned__int128 est sur seulement 39 digits . Merci. bon courage.

**Comment by guyfrancoeur** [comment]
NON !

**Comment by charimene** [comment]
Super merci Mr Guy :)

**Comment by leohersant** [comment]
Bonjour,
je travaille avec les nombres  unsigned__int128 et j'ai découvert ceci:

atoi(18446744073709551615) me donne 340282366920938463463374607431768211455.

je m'explique:

unsigned__int128 x = 0;
x = atoi(340282366920938463463374607431768211455); // 128 bits
// la valeur de x après est 340282366920938463463374607431768211455

ce que je ne comprends pas c'est:

unsigned__int128 x = 0;
x = atoi(18446744073709551615); // 64 bits
// **la valeur de x après est 340282366920938463463374607431768211455**


à quoi c'est dû? qu'est-ce que je suis entrain de manquer? Pouvez vous montrer un exemple en classe de comment manipuler ces quantités?

Merci!

**Comment by dbrsseau** [comment]
@josuetorr  la fonction `printU128(&n)` est-ce une fonction personnelle ou ça provient d'une librairie quelconque ?

**Comment by josuetorr** [comment]
@dbrsseau personnelle, je l’ai écrit moi-même

**Comment by dbrsseau** [comment]
@josuetorr @guyfrancoeur est-ce qu'il y aurait un problème à utiliser l'alternative suivante `printf("%ju", (uintmax_t)n)` qui est définie dans la librairie `stdint.h` ? Pour l'instant, ça fait ce que je veux et je n'ai aucun "warning" qui s'affiche. Cette fonction `printU128(n)` est-ce une exigence particulière du TP3 ?

**Comment by josuetorr** [comment]
@dbrsseau uintmax_t est un entier de 64 bits. Nous travaillons avec des entiers avec 128 bits. Tu n’as pas le choix d’impleme Ta propre fonction.

**Comment by dbrsseau** [comment]
@josuetorr encore une fois merci ! Je n'avais pas encore testé un très grand nombre... Je me suis arrêté au "warning" seulement... Je viens de le tester correctement et effectivement ça ne marche plus ! Merci pour l'info !
