### ISSUE TITLE
Question par rapport à l'option -d

### ISSUE THREAD

**Issue by tannazhz** [guyfrancoeur/INF3135_H2019_TP3#5]
Bonjour,
si nous omettons l'option`-d` de notre ligne de commande, par défaut ça sera par ordre décroissant, mais si l'on met `-d` suivi de rien du tout, devons-nous retourner le code d'erreur 7 ou devons-nous afficher les nombres par ordre décroissant (donc par défaut) ?

merci

**Comment by guyfrancoeur** [comment]
Oui svp.

On dira que la précondition n'est pas satisfaite. donc il y a bris de contrat.
