### ISSUE TITLE
test No 32 dans le fichier de correction 

### ISSUE THREAD

**Issue by ahmedsalia** [guyfrancoeur/INF3135_H2019_TP3#6]
Bonsoir :) 

Ne pensez vous pas que le test 32 du fichier inf3135-h2019-tp3.correction crée une boucle infinie ? 

1 99 0 evaluer.sh (excute)   ./evaluer.sh > evaluer-tp2.guy

Merci ! :)

**Comment by guyfrancoeur** [comment]
@ahmedsalia 

Possible, 👍 Bravo pour la découverte et, ou, réflexion.

+ Q1. Mais dans quel cas est-il est possible d'avoir une bouble infini?
+ Q2. Est-ce possible de prevenir ceci ?

Certains ont executé le script sans vérifier vous devez tuer vos processus dans JAVA dans les plus bref délais. 
+ Q3. Quelle est la procédure complete pour voir et tuer les processus (actifs) dans JAVA?

**Comment by ahmedsalia** [comment]
Bonjour Professeur @guyfrancoeur ,
 

- R1. La boucle infinie est présente car le fichier script evaluer.sh se lance elle même de ce fait, le fichier script ne va jamais arrêter de rouler. 


- R2. Pour prévenir ceci, la réponse la plus rapide serais surement de modifier la ligne 32 pour qu'elle ne "Re-run" pas encore le fichier script mais juste envoyer le résultat dans evaluer-tp2.guy. 

- R3. J'ai fais quelque recherche, et pour tuer des processus actifs dans Java, il faut : Fermer l'entrée et la sortie standard du process et utiliser la méthode destroy dessus.

- R4. On ne peut pas modifier evaluer.sh car notre programme doit être assez solide pour passez n'importe quelle tests et aussi, c'est une script dynamique donc on doit juste télécharger le fichier de test 

- R5. La question n'est as un peu trop vague ? Je dirais c'est avoir un programme de haute qualité et  aucune fuite de mémoire.

**Comment by guyfrancoeur** [comment]
Reponses:

@ahmedsalia 

R1 : 
+ a) Si on lance `evaluer.sh` avec le `inf3135-h2019-tp3.correction`
+ b) `evaluer.sh` n'est pas fait pour cela!

R2 : 
+ a) Oui par la vérification du fichier de correction.

R3 : 
 + a) les commandes suivantes sont nécessaires : `ps`, `kill`, 
 + b) facultatives : `htop`, `fg`

R4 : 
+ a) Enfin vous pouvez le corriger `evaluer.sh` mais pas changer le fichier de données (correction) requis pour son exécution.
+ b) Il faut maintenir les données d'entrées tel quel pour les tests de regression.

R5 : 
+ a) créer un `evaluer-tp3.sh` pour faire les tests.
+ b) c'est lui qui va ouvrir inf3135-h2019-tp3.correction et exécuter les tests.

**Comment by LauriGui** [comment]
C’est justement ce que je m’étais demandé, s’il fallait ajouter `evaluer-tp3.sh`, dans notre projet, pour le tp2 😅 et donc, puisqu’on doit le faire, doit-on aussi ajouter `evaluer.sh`, dans notre projet de tp3? 

Aussi, lorsque nous exécuterons les tests, pour le tp3, les `./tp2` seront-ils changés pour `./tp3`?

Par contre, cela impliquerait aussi des modifications, dans le fichier `inf3135-h2019-tp2.correction`, si nous voulons vraiment tester notre tp3...

Finalement, pour le test 8, j’ai remarqué qu’il y avait la validation, à savoir si le répertoire `data` était encore existant, après `make clean`, mais il me semble que les seuls fichiers qui étaient à supprimer, avec cette commande, devaient être `code.txt` et l’exécutable `tp2`... C’est pourquoi, je m’étais créée une autre cible, pour supprimer, entre autres, le dossier `data`...

**Comment by LauriGui** [comment]
De plus, comme le test 34 vérifie le format de sortie des résultats, ça veut dire que nous devons vraiment reproduire exactement le même format que dans l'exemple de l'énoncé du tp (sans personnalisation, excepté pour notre code permanent)?

Merci!

**Comment by guyfrancoeur** [comment]
Allo @LauriGui,

Tu as répondu à la majorité en posant la question. Ça va de soi!

La réponse principale à tes questions est un lien symbolique appelé `tp2` qui pointe vers `tp3`

```bash
clean :
        ... va faire le nécessaire pour garder le répertoire propre

tp3 : aura une dépense sur tp2
        gcc ... 

tp2 : 
        ... on va mettre quelque chose ici. voir plus haut !
```

`./evaluer.sh` est bien sûr redirigé... nous sommes en `bash Linux` ... les redirections sont importantes et utiles.  Vous aurez compris que c'est le moyen pour consulter et valider ce que produit le script `evaluer.sh`.

Sans être directif, car vous êtes toujours libre de faire ce qui vous plaît, il est recommandé de faire ce qui est suggéré.  Si je prend du temps en classe et dans les énoncés pour faire des exemples, je crois, qu'une bonne première version est de reproduire le plus fidèlement possible la suggestion.  Le MARCHÉ travaille exactement de cette façon.  Pas de suggestion veut dire : trouver le standard et reproduisez-le.  Pas de standard, pas de suggestion ... Vous pouvez imaginer !  hihi...

**Comment by LauriGui** [comment]
Merci @guyfrancoeur !

Ah ok, je viens de comprendre, pour la redirection de `./evaluer.sh`. Je croyais que vous vouliez dire que c'était la commande à exécuter, pour vous remettre le fichier `evaluer-tp2.guy` imprimé.

Cependant, je comprends très bien qu'il ne faut pas changer `./evaluer.sh`, mais c'est plutôt `inf3135-h2019-tp2.correction` et `inf3135-h2019-tp3.correction` qui m'intriguaient, je me demandais s'ils seraient changés, pour les tests du tp3, car notre exécutable change de nom...? Si c'est moi qui n'ai juste pas bien compris que votre réponse à cette question se trouve dans les liens symboliques, c'est correct, c'est là que je vais chercher! 😊

**Comment by dychen23** [comment]
pas sur si je dois ouvrir un autre issue vu que celui-la est "closed", mais j'ai quelque question sur le test numero 32.

1. Si je comprend bien, on a un fichier evaluer-tp3,sh ET un evaluer.sh ? 
2. On n'a pas besoin de faire un lien symbolic sur evaluer-tp3.sh si on a un fichier evaluer.sh ?
3. Si on appelle  kill -9 `ps -aux | grep "codeMS" | grep "evaluer" | awk '{print $2}'`, ca ne va pas kill tous les scripts evaluer.sh incluant evaluer-tp3.sh?

**Comment by LauriGui** [comment]
@dychen23

1. Oui

2. Non, mais je ne comprends pas pourquoi tu voudrais en faire un..?

3. Je ne crois pas non, mais je ne suis pas sûre...

**Comment by dychen23** [comment]
@LauriGui 

2. j'ai cru que c'etait necessaire de faire un lien symbolique parce que je n'avais pas penser a creer un autre evaluer.sh, j'etais jeune et naive

3. Je me suis creer un script qui s'appele kill.sh avec ligne kill -9  `ps aux | grep root | grep "evaluer" | awk '{print $2}'`, puis ca kill le evaluer-tp3.sh ainsi que evaluer.sh, qui cree la boucle.

**Comment by LauriGui** [comment]
@dychen23 

3. Mais en fait, si tes scripts s'exécutent comme prévu, tu ne devrais pas avoir de boucle infini, sur `evaluer.sh`... Dans le fond, ton script `kill.sh` servirait que pour supprimer des processus qui continuent de rouler, sans que ce soit prévu, mais autrement, si tout se passe bien, tu ne devrais pas avoir à supprimer des processus... (Avec `timeout`, ils sont supprimé tout seuls... Tu peux aller voir `man timeout`, pour plus d'informations, à ce propos 😉)
