### ISSUE TITLE
Intervalle valide

### ISSUE THREAD

**Issue by sanajaziri** [guyfrancoeur/INF3135_H2019_TP3#9]
Bonjour;
Je veux savoir si un intervalle avec des espaces avant le 1er nombre et après le 2eme nombre est valide?
Exemple:
Est ce que cet intervalle est valide?
     1111           9999999                 '\n'

**Comment by guyfrancoeur** [comment]
Bonjour,

Il me semble que oui. Êtes vous en mesure de le gérer ?

**Comment by sanajaziri** [comment]
Bonjour,
Oui.
